'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ISLAMIC_BOOKSTOREEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ISLAMIC_BOOKSTOREEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tMENUs() As DbSet(Of tMENU)
    Public Overridable Property tCODEs() As DbSet(Of tCODE)
    Public Overridable Property tROLEs() As DbSet(Of tROLE)
    Public Overridable Property tROLESMENUs() As DbSet(Of tROLESMENU)
    Public Overridable Property tASSIGNMENTs() As DbSet(Of tASSIGNMENT)
    Public Overridable Property vMYROLEs() As DbSet(Of vMYROLE)
    Public Overridable Property tITEM_DETAIL() As DbSet(Of tITEM_DETAIL)
    Public Overridable Property tCARTs() As DbSet(Of tCART)
    Public Overridable Property tITEMs() As DbSet(Of tITEM)
    Public Overridable Property tPURCHASINGs() As DbSet(Of tPURCHASING)
    Public Overridable Property tUSERs() As DbSet(Of tUSER)
    Public Overridable Property tDOCUMENTs() As DbSet(Of tDOCUMENT)

End Class
