'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tASSIGNMENT
    Public Property ASSIGNMENT_ID As Integer
    Public Property USER_ID As String
    Public Property ROLE_CODE As String

End Class
Partial Public Class tCART
    Public Property CART_ID As String
    Public Property USER_ID As String
    Public Property ITEM_ID As String
    Public Property ITEM_STATUS As String
    Public Property ITEM_QTY As Decimal
    Public Property ITEM_PRICE As Decimal
    Public Property TOTAL_PRICE As Decimal
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date
    Public Property UPDATEDBY As String
    Public Property UPDATEDDATE As Nullable(Of Date)

    Public Overridable Property tPURCHASINGs As ICollection(Of tPURCHASING) = New HashSet(Of tPURCHASING)

End Class
Partial Public Class tCODE
    Public Property C_ID As Integer
    Public Property C_CODE As String
    Public Property C_DESCRIPTION As String
    Public Property C_GROUP As String
    Public Property C_ORDER As Nullable(Of Integer)
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date

End Class
Partial Public Class tDOCUMENT
    Public Property FILE_ID As String
    Public Property ITEM_ID As String
    Public Property FILE_NAME As String
    Public Property FILE_NAME_ORI As String
    Public Property FILE_PATH As String
    Public Property FILE_TYPE As String
    Public Property FILE_SIZE As Nullable(Of Double)
    Public Property CUR_FILE As Nullable(Of Boolean)
    Public Property UPLOADBY As String
    Public Property UPLOADDATE As Nullable(Of Date)

    Public Overridable Property tITEM As tITEM

End Class
Partial Public Class tITEM
    Public Property ITEM_ID As String
    Public Property ITEM_NAME As String
    Public Property ITEM_QTY As Decimal
    Public Property TOTAL_QTY As Decimal
    Public Property PURC_QTY As Decimal
    Public Property BAL_QTY As Decimal
    Public Property ITEM_UNIT As String
    Public Property ITEM_PRICE As Decimal
    Public Property TOTAL_PRICE As Decimal
    Public Property ITEM_STATUS As String
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date
    Public Property UPDATEDBY As String
    Public Property UPDATEDDATE As Nullable(Of Date)

    Public Overridable Property tITEM_DETAIL As ICollection(Of tITEM_DETAIL) = New HashSet(Of tITEM_DETAIL)
    Public Overridable Property tDOCUMENTs As ICollection(Of tDOCUMENT) = New HashSet(Of tDOCUMENT)

End Class
Partial Public Class tITEM_DETAIL
    Public Property DETAIL_ID As String
    Public Property ITEM_ID As String
    Public Property KATEGORI As String
    Public Property PENERBIT As String
    Public Property KONDISI As String
    Public Property BAHAN As String
    Public Property DETIL_PRODUK As String
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date
    Public Property UPDATEDBY As String
    Public Property UPDATEDDATE As Nullable(Of Date)
    Public Property FOLDER_PAGE As String
    Public Property APPLICATION_PAGE As String

    Public Overridable Property tITEM As tITEM

End Class
Partial Public Class tMENU
    Public Property MENU_ID As Integer
    Public Property PARENT_ID As Nullable(Of Integer)
    Public Property MENU_DESCRIPTION As String
    Public Property MENU_VALUE As String
    Public Property MENU_URL As String
    Public Property MENU_ORDER As Nullable(Of Integer)
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date

End Class
Partial Public Class tPURCHASING
    Public Property PURC_ID As String
    Public Property CART_ID As String
    Public Property PAYMENT_DATE As Date
    Public Property PAYMENT_STATUS As String

    Public Overridable Property tCART As tCART

End Class
Partial Public Class tROLE
    Public Property ROLE_ID As Integer
    Public Property ROLE_CODE As String
    Public Property ROLE_DESCRIPTION As String
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date

End Class
Partial Public Class tROLESMENU
    Public Property RM_ID As String
    Public Property MENU_ID As Integer
    Public Property ROLE_CODE As String
    Public Property [SELECT] As Nullable(Of Boolean)
    Public Property INSERT As Nullable(Of Boolean)
    Public Property UPDATE As Nullable(Of Boolean)
    Public Property DELETE As Nullable(Of Boolean)
    Public Property REPORT As Nullable(Of Boolean)
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date
    Public Property UPDATEDBY As String
    Public Property UPDATEDDATE As Nullable(Of Date)

End Class
Partial Public Class tUSER
    Public Property USER_ID As String
    Public Property USER_NAME As String
    Public Property MULTIROLE As Boolean
    Public Property USER_ROLE As String
    Public Property USER_ADDRESS As String
    Public Property USER_MOBILE As String
    Public Property USER_MAIL As String
    Public Property USER_PASSWORD As String
    Public Property CREATEDBY As String
    Public Property CREATEDDATE As Date
    Public Property UPDATEDBY As String
    Public Property UPDATEDDATE As Nullable(Of Date)

End Class
Partial Public Class vMYROLE
    Public Property ASSIGNMENT_ID As Integer
    Public Property USER_ID As String
    Public Property USER_NAME As String
    Public Property USER_MAIL As String
    Public Property USER_MOBILE As String
    Public Property ROLE_CODE As String
    Public Property ROLE_DESCRIPTION As String

End Class
